---
- name: Download WP-CLI
  shell: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  args:
      chdir: /vagrant

- name: Make WP-CLI executable
  file:
    path: /vagrant/wp-cli.phar
    mode: u=rwx,g=rx,o=rx

- name: Move WP-CLI to /usr/local/bin/wp
  command: mv /vagrant/wp-cli.phar /usr/local/bin/wp
  become: yes
